name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    # env:
    # YAEGI_VERSION: v0.14.2
    # defaults:
    #   run:
    #     working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"

      - name: Check and get dependencies
        run: |
          go mod download
          go mod vendor
          go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      # - name: Install Yaegi ${{ env.YAEGI_VERSION }}
      #   run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}

      # - name: Run tests with Yaegi
      #   run: make yaegi_test
      #   env:
      #     GOPATH: ${{ github.workspace }}/go
